# Generated by Django 5.1.4 on 2025-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
        ('portfolio', '0007_technology_certification_image_certification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='portfolio.category'),
        ),
    ]
