# Generated by Django 5.1.4 on 2025-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_slug_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='ML', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
    ]
